### ISSUE TITLE
Add option for more verbosity in verify-evaluate-cloud-metrics/main.go

### ISSUE THREAD

**Issue by palladius** [GoogleCloudPlatform/cloud-deploy-samples#31]
I'm playing wround with `verify-evaluate-cloud-metrics/`.
It's beautiful but i keep getting -1 in the verify part. So I decided to invoke the verify stanza locally.

I'm calling `skaffold verify` locally since i keep getting errors

I use the native skaffold.yaml, I just needed to inject manually the project since Cloud Deploy uses ENV to do it and I was unable to put ENV in the skaffold render stanza (or CLI):

```yaml
apiVersion: skaffold/v4beta4
kind: Config
manifests:
  rawYaml:
  - run.yaml
# deploy:
#   cloudrun: {}
deploy:
  cloudrun:
    region: us-central1
    projectid: rick-and-nardy-demo
verify:
- name: verify-requests-are-not-5xx
  container:
    name: verify-requests
    #image: "us-central1-docker.pkg.dev/rick-and-nardy-demo/ricc-verify-demo/ricc-verify-test@sha256:e4012ff0f0d8dd851921650f9167a974064b2fda6f89b459f36404ee0865a80e"
    image: "us-central1-docker.pkg.dev/rick-and-nardy-demo/ricc-verify-demo/ricc-verify-test:latest"
    #image: us-central1-docker.pkg.dev/rick-and-nardy-demo/ricc-verify-demo/ricc-verify-test
    command: ["./verify-evaluate-cloud-metrics"]
    args:
    - --project=rick-and-nardy-demo
    - --table-name=cloud_run_revision
    - --metric-type=run.googleapis.com/request_count
    - --predicates=resource.location=='us-central1',resource.service_name=='hello-app' # filter out metrics for `hello-app` in `us-west2`
    - --refresh-period=1m
    - --sliding-window=1m
    - --max-error-percentage=15 # verify that less than 15% of the requests are 5xx errors
```

```bash
$ skaffold verify 
latest: Pulling from rick-and-nardy-demo/ricc-verify-demo/ricc-verify-test
Digest: sha256:e4012ff0f0d8dd851921650f9167a974064b2fda6f89b459f36404ee0865a80e
Status: Image is up to date for us-central1-docker.pkg.dev/rick-and-nardy-demo/ricc-verify-demo/ricc-verify-test:latest
[verify-requests-are-not-5xx] ---
[verify-requests-are-not-5xx] Verification configured as follows:
[verify-requests-are-not-5xx] Project: "rick-and-nardy-demo"
[verify-requests-are-not-5xx] Table Name: "cloud_run_revision"
[verify-requests-are-not-5xx] Metric Type: "run.googleapis.com/request_count"
[verify-requests-are-not-5xx] Predicates: "resource.location=='us-central1',resource.service_name=='hello-app'"
[verify-requests-are-not-5xx] Response Code Class: "5xx"
[verify-requests-are-not-5xx] Max Error Percentage: 15
[verify-requests-are-not-5xx] Sliding Window: 1m0s
[verify-requests-are-not-5xx] Trigger Duration: 5m0s
[verify-requests-are-not-5xx] Time To Monitor: 20m0s
[verify-requests-are-not-5xx] Refresh Period: 1m0s
[verify-requests-are-not-5xx] ---
1 error(s) occurred:
* verify test failed: "verify-requests-are-not-5xx" running container image "us-central1-docker.pkg.dev/rick-and-nardy-demo/ricc-verify-demo/ricc-verify-test:latest" errored during run with status code: 1
```

Note that the input is beautiful shown but I have no idea / nor output why the system failed with -1.

Since I tell you "max-error-percentage=15" I'd like to know if it failed because the error rate is above 15 or for some other reason.
And I'm no golang programmer to help fixing it.
